$linkedData:
  term: ProductRegistrationCredential
  '@id': https://w3id.org/traceability#ProductRegistrationCredential
title: Product Registration Credential
description: Ecommerce Product Registration Credential
type: object
properties:
  type:
    oneOf:
      - type: array
      - type: string
        enum:
          - ProductRegistrationCredential
  productCode:
    title: productCode
    description: Product ID either GTIN or UPC
    type: number
    $linkedData:
      term: productCode
      '@id': https://schema.org/productID
  productCodeType:
    title: productCodeType
    description: Product ID Type either GTIN or UPC
    type: string
    $linkedData:
      term: productCodeType
      '@id': https://schema.org/additionalType
  certificateName:
    title: certificateName
    description: Specific name of issued product registration certificate
    type: string
    $linkedData:
      term: certificateName
      '@id': https://schema.org/name
required:
  - productCode
  - productCodeType
  - certificateName
additionalProperties: false
example: |-
  {
    "type": "ProductRegistrationCredential",
    "productCode": 10,
    "productCodeType": "UPC",
    "certificateName": "ACME Product Registration Certificate"
  }
